// GENERATED by tools/scripts/rename/rename_hmac.sh -- do not edit by hand.
// Compile-ordered filelist for the imported hmac block.
+incdir+${ARCA_ROOT}/rtl/hmac
${ARCA_ROOT}/rtl/hmac/arca_hmac_config.svh
${ARCA_ROOT}/rtl/hmac/arca_hmac_param_pkg.sv
${ARCA_ROOT}/rtl/hmac/arca_hmac_reg_pkg.sv
${ARCA_ROOT}/rtl/hmac/arca_hmac_ctrl.sv
${ARCA_ROOT}/rtl/hmac/arca_hmac.sv
${ARCA_ROOT}/rtl/hmac/arca_hmac_core.sv
${ARCA_ROOT}/rtl/hmac/arca_hmac_reg.sv
${ARCA_ROOT}/rtl/hmac/arca_hmac_drbg.sv
