// GENERATED by tools/scripts/rename/rename_ecc.sh -- do not edit by hand.
// Compile-ordered filelist for the imported ecc block.
+incdir+${ARCA_ROOT}/rtl/ecc
${ARCA_ROOT}/rtl/ecc/arca_ecc_reg_pkg.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_defines_pkg.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_params_pkg.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_dsa_uop_pkg.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_pm_uop_pkg.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_top.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_reg.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_dsa_ctrl.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_dsa_sequencer.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_scalar_blinding.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_hmac_drbg_interface.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_arith_unit.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_pm_ctrl.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_pm_sequencer.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_ram_tdp_file.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_fau.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_montgomerymultiplier.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_pe_first.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_pe.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_pe_final.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_mult_dsp.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_add_sub_mod_alter.sv
${ARCA_ROOT}/rtl/ecc/arca_ecc_adder.sv
