// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/scripts/rename/rename_hmac512.sh -- do not edit by hand.
//
// Configuration macros that the caliptra-rtl *environment* used to apply to
// the hmac512 block. They are captured here, under the Tessera prefix, so the imported
// block no longer depends on caliptra-rtl global headers.
//
`ifndef TESSERA_HMAC512_CONFIG_SVH
`define TESSERA_HMAC512_CONFIG_SVH

// from src/libs/rtl/caliptra_macros.svh
  `define TESSERA_CLP_CSR_HMAC_KEY_DWORDS 16

`endif // TESSERA_HMAC512_CONFIG_SVH
